### ISSUE TITLE
Example List of services

### ISSUE THREAD

**Issue by RBN2208** [RBN2208/capstone-project#1]
**Value statement**
**As** a user,
**I** would like to have a list with workservices,
**wich** show my their cost value when i click the service.

**Description (Text, Scribble, Wireframe, Design)**

<img width="184" alt="Screenshot 2021-03-06 at 12 41 53" src="https://user-images.githubusercontent.com/77283667/110205646-886e3a80-7e79-11eb-917c-955e2e3ced5d.png">

**Acceptance criteria**

- [x] The name of the service is visible.
- [x] The costvalue of the service is also visible, when the service card is clicked

**Tasks**

- [x] Create feature branch
- [x] Create a examplelist with services and costvalues
- [x] Create Servicecard component in Storybook
- [x] Write component tests
- [x] Add components to app (feature implementation with state)
- [x] Create function for show/hide on click
- [x] Add missing styles

**Complexity**
low
