### ISSUE TITLE
The displayed costvalue should only be displayed, when the servicecard is clicked.

### ISSUE THREAD

**Issue by RBN2208** [RBN2208/capstone-project#11]
**Description (Text, Scribble, Wireframe, Design)**

**Acceptance criteria**

The name of the service is visible.
The costvalue of the service is also visible.

**Tasks**

- [ ] Create feature branch
- [ ] Create a examplelist with services and costvalues
- [ ] Create Servicecard component in Storybook
- [ ] Write component tests
- [ ] Add components to app (feature implementation with state)
- [ ] Add missing styles

**Complexity**
low
