### ISSUE TITLE
Delete Services

### ISSUE THREAD

**Issue by RBN2208** [RBN2208/capstone-project#14]
As a user, i want to delete some of my old calculations and my services, so i get a better overview.

**Description (Text, Scribble, Wireframe, Design)**

<img width="701" alt="Screenshot 2021-03-19 at 16 30 25" src="https://user-images.githubusercontent.com/77283667/111804518-71dfce80-88d0-11eb-9c76-2a1a4b28f576.png">

**Acceptance criteria**

- [x] The History displays my last calculations
- [x] There is a delete button for each service
- [x] there is a delete button for each history entry

**Tasks**

- [x] Create feature branch
- [x] Implement button
- [x] implement delete logic
- [x] Write component tests
- [x] Add components to app (feature implementation with state)
- [x] Add missing styles

**Complexity**
medium
