### ISSUE TITLE
Optional Infotext for each service

### ISSUE THREAD

**Issue by RBN2208** [RBN2208/capstone-project#15]
As a user, i want to add infos for my services

**Description (Text, Scribble, Wireframe, Design)**

<img width="466" alt="Screenshot 2021-03-19 at 16 33 32" src="https://user-images.githubusercontent.com/77283667/111805002-eb77bc80-88d0-11eb-94e5-758730c7488d.png">

**Acceptance criteria**

- [x] There is a new input when creating a new service
- [x] The given input will be displayed on the servicecard

**Tasks**

- [x] Create feature branch
- [x] Implement input
- [x] implement logic to get inputvalue
- [x] Write component tests
- [x] Add components to app (feature implementation with state)
- [x] Add missing styles

**Complexity**
medium
