### ISSUE TITLE
Landingpage

### ISSUE THREAD

**Issue by RBN2208** [RBN2208/capstone-project#16]
Landing page with an info text about the usage of the app

**Description (Text, Scribble, Wireframe, Design)**

<img width="318" alt="Screenshot 2021-03-26 at 15 51 50" src="https://user-images.githubusercontent.com/77283667/112649942-35215380-8e4b-11eb-96ba-268d42c55462.png">

**Acceptance criteria**

- [x] there is a landing page
- [x] it´s no login!
- [x] there is loading bar

**Tasks**

- [x] Create feature branch
- [x] create landingpage
- [x] Write component tests
- [x] Add components to app (feature implementation with state)
- [x] Add missing styles

**Complexity**
medium
