### ISSUE TITLE
Searchbar

### ISSUE THREAD

**Issue by RBN2208** [RBN2208/capstone-project#19]
As a user, i need a searchbar, so i can find my services faster

**Description (Text, Scribble, Wireframe, Design)**

<img width="198" alt="Screenshot 2021-03-21 at 12 54 47" src="https://user-images.githubusercontent.com/77283667/111903919-a2e11000-8a44-11eb-9157-ed5b85bbd59a.png">

**Acceptance criteria**

- [x] there is searchbar
- [x] the searchbar filters on input by name

**Tasks**

- [x] Create feature branch
- [x] create searchbar
- [x] implement searchbar
- [x] write logic for searchbar
- [x] Write component tests
- [x] Add components to app (feature implementation with state)
- [x] Add missing styles

**Complexity**
medium
