### ISSUE TITLE
Add cards to shopping cart

### ISSUE THREAD

**Issue by RBN2208** [RBN2208/capstone-project#2]
## Value Statement ##
**As** a user, 
i want to add and substrate services,
to get a costvalue result

## Description (Text, Scribble, Wireframe, Design) ##

<img width="253" alt="Screenshot 2021-03-08 at 15 17 52" src="https://user-images.githubusercontent.com/77283667/110333270-b2faf780-8021-11eb-9bd2-6979abc18fdd.png">

## Acceptance criteria ##

- [x] There is a button to add a value
- [x] There is a button to substrate a value
- [x] The final result will be displayed
- [x] A selectet service is highlighted

## Tasks ##

- [x] Create feature branch
- [x] Add Buttons in Storybook
- [x] Update Servicecard in Storybook
- [x] Add math logic
- [x] Write component tests
- [x] Add components to app (feature implementation with state)
- [x] Add missing styles

- [x] Added a Counter to see how often a service is added 
- [x] Logic so the counter cant go negative

## Complexity ##
low +2
