### ISSUE TITLE
Updatet save result

### ISSUE THREAD

**Issue by RBN2208** [RBN2208/capstone-project#20]
As a user, i want to add a keyword to my saved results, so i get an better overview

**Description (Text, Scribble, Wireframe, Design)**

<img width="593" alt="Screenshot 2021-03-21 at 12 56 57" src="https://user-images.githubusercontent.com/77283667/111904033-08cd9780-8a45-11eb-84bc-007ef579427f.png">

**Acceptance criteria**

- [x] There is an textarea in the safe result form
- [x] It´s an required textfield
- [x] the value of the textfield get displayed over it´s own historyentry

**Tasks**

- [x] Create feature branch
- [x] implement inputfield
- [x] implement logic
- [x] Write component tests
- [x] Add components to app (feature implementation with state)
- [x] Add missing styles

**Complexity**
medium
