### ISSUE TITLE
detailed historyentrys

### ISSUE THREAD

**Issue by RBN2208** [RBN2208/capstone-project#21]
As a user, i want to see more informations in my history, like a list with all services wich i used for caculation

**Description (Text, Scribble, Wireframe, Design)**

<img width="467" alt="Screenshot 2021-03-21 at 13 00 40" src="https://user-images.githubusercontent.com/77283667/111904144-94dfbf00-8a45-11eb-8f05-63ac94b5ae61.png">

**Acceptance criteria**

- [x] There is a "Info"-Button
- [x] a box opens with a list of services for each history

**Tasks**

- [x] Create feature branch
- [x] implement button
- [x] implement logic
- [x] Write component tests
- [x] Add components to app (feature implementation with state)
- [x] Add missing styles

**Complexity**
medium
