### ISSUE TITLE
Add a new card

### ISSUE THREAD

**Issue by RBN2208** [RBN2208/capstone-project#3]
## Value Statement ##

**As** a user i want to add my own services,
**They** should contain a name, my costs and each click should represent my time in hours

**Description (Text, Scribble, Wireframe, Design)**

<img width="643" alt="Screenshot 2021-03-10 at 12 30 42" src="https://user-images.githubusercontent.com/77283667/110622969-76074000-819c-11eb-995b-28bc96b40f06.png">

## Acceptance criteria ##

- [x] There is a button for a new entry.
- [x] The Button opens a new form
- [x] The form has inputs for a "name", "estimated hours" and "costvalue"
- [x] It has a submit button

## Tasks ##

- [x] Create feature branch
- [x] Create the Form with a button in storybook
- [x] Update other components
- [x] Logic for new cards on submit
- [x] Logic to save to local
- [x] Write component tests
- [x] Add components to app (feature implementation with state)
- [x] Add missing styles

**Complexity**
medium
