### ISSUE TITLE
Save Result to history

### ISSUE THREAD

**Issue by RBN2208** [RBN2208/capstone-project#4]
As a user, i want to save my calculations, so i can see what i did in the past.

**Description (Text, Scribble, Wireframe, Design)**

<img width="561" alt="Screenshot 2021-03-15 at 11 55 11" src="https://user-images.githubusercontent.com/77283667/111142744-5188da80-8585-11eb-9c11-973fd6a4427f.png">

**Acceptance criteria**

- [x] There is a page for a history
- [x] I need a navigation to the historypage
- [x] From the History i get back to my home
- [x] When i click on a button, my result will get saved to the history

**Tasks**

- [x] Create feature branch
- [x] create the different pages
- [x] create a navigation
- [x] implement react router
- [x] update Servicecard component in Storybook
- [x] Create Storybook Components
- [x] Write component tests
- [x] Add components to app (feature implementation with state)
- [x] Add missing styles

**Complexity**
low
