### ISSUE TITLE
History

### ISSUE THREAD

**Issue by RBN2208** [RBN2208/capstone-project#5]
As a user, i want to delete some of my old calculations, so i get a better overview.

**Description (Text, Scribble, Wireframe, Design)**

<img width="613" alt="Screenshot 2021-03-15 at 11 58 26" src="https://user-images.githubusercontent.com/77283667/111143162-c6f4ab00-8585-11eb-8a18-6658aaed5b81.png">

**Acceptance criteria**

- [x] The History displays my last calculations
- [ ] there is a button to delete a historyentry

**Tasks**

- [ ] Create feature branch
- [ ] Create the Form with a button in storybook
- [ ] Write component tests
- [ ] Add components to app (feature implementation with state)
- [ ] Add missing styles

**Complexity**
medium

**Comment by RBN2208** [comment]
Outdatet, gets replaced with [https://github.com/RBN2208/capstone-project/issues/14]
